models/postsModel.js
models/userModel.js

更新userModel與postModel

---

routes/index.js
routes/posts.js

refactor: 重構 routes

---

controller/file_controller.js
controller/follow_controller.js
controller/post_controller.js
controller/user_controller.js
routes/index.js
routes/posts.js

refactor: 重構 controller

---

utils/errorHandler.js

更新 - 針對 appError 添加描述

---

controller/follow_controller.js
controller/post_controller.js
controller/user_controller.js
middleware/auth.js
routes/users.js
utils/passport.js

修正 - 少填一個單引號

---

models/commentModel.js
models/followModel.js
models/postModel.js
models/userModel.js

更新 - 添加 updatedAt 和 logicDeleteFlag 到所有 model

---

controller/postController.js
routes/posts.js

feat: 新增 api - 新增貼文

---

models/commentModel.js
models/followModel.js
models/postModel.js
models/userModel.js

refactor：重構 Schema logicDeleteFlag

---

controller/postController.js

fix: 新增貼文 API

---

models/commentModel.js
models/postModel.js
models/userModel.js

refector: 重構 Schema

---

controller/postController.js
routes/posts.js

feat: 修改貼文 API

---

.gitignore
controller/postController.js
models/commentModel.js
models/postModel.js
models/userModel.js
routes/posts.js

Dev - 取得全部貼文或個人全部貼文

---

models/postModel.js

fix: 修正 Schema - comments

---

controller/commentController.js

fix: 新增一則貼文的留言 API

---

controller/commentController.js
routes/posts.js

feat: 修改一則貼文的留言 API

---

controller/commentController.js
package-lock.json
routes/posts.js

feat: 刪除一則貼文的留言 API

---

controller/postController.js

1. 新增 sort=hot 的排序條件
2. 預設排序條件改為 desc

Dev-andy-新增 sort=hot 的排序條件 & 預設排序條件改為 desc

---

controller/followController.js

fix: 修正 response 格式

---

controller/commentController.js
controller/fileController.js
controller/followController.js
controller/likeController.js
controller/postController.js
controller/userController.js
routes/posts.js
routes/users.js

fix: 修正 routes、controller

---

routes/auth.js

fix: 修正 cookie 名稱為 google-token

fix: 修正 cookie 名稱為 google-token

---

.eslintrc.js
package-lock.json
package.json

feat: 加上基礎的 eslint 設定

---

app.js
connections/index.js
controller/authController.js
controller/commentController.js
controller/fileController.js
controller/followController.js
controller/likeController.js
controller/postController.js
controller/userController.js
middleware/auth.js
middleware/checkId.js
models/commentModel.js
models/followModel.js
models/postModel.js
models/userModel.js
routes/auth.js
routes/general.js
routes/index.js
routes/posts.js
routes/users.js
utils/errorHandler.js
utils/passport.js
utils/process.js
utils/successHandler.js
utils/upload.js
utils/validator.js

1.  /post 將一同取得的 comments 按照時間排序(新到舊)

Dev-將一同取得的 comments 按照時間排序(新到舊)

---

controller/userController.js

fix: 修改 userController.js

---

controller/postController.js

fix: 修正 postController.js

---

controller/likeController.js

fix: 修改 likeController.js

---

controller/fileController.js
utils/upload.js

fix: 修改 fileController.js

---

controller/commentController.js

fix: 修改 commentController.js

---

app.js
routes/auth.js
routes/general.js
routes/posts.js
routes/users.js

fix: 修改 routes

---

controller/userController.js

fix: 修正 userController.js 寫作風格

---

controller/postController.js

fix: 修正 postController.js 寫作風格

---

controller/likeController.js

fix: 修正 likeController.js 寫作風格

---

controller/commentController.js

fix: 修正 commentController.js 寫作風格

---

controller/commentController.js
models/commentModel.js
models/postModel.js

fix: 修改 Model、commentController.js

---

app.js
controller/likeController.js

1. 修正 like controllers 的查找和回傳問題

1. fix like controllers

---

controller/commentController.js

Dev-fix postComment controller

---

app.js
controller/userController.js
middleware/auth.js
middleware/checkId.js
routes/users.js
swagger-defintion.js
swagger-output.json
swagger.js

新增 swagger 文件 - userController.js

feat: swagger 文件 - userController.js

---

controller/postController.js
controller/userController.js
routes/posts.js
swagger-defintion.js
swagger-output.json

新增 swagger 文件 - postController.js

feat: swagger 文件 - postController.js

---

controller/likeController.js
controller/userController.js
routes/posts.js
swagger-defintion.js
swagger-output.json

新增 swagger 文件 - likeController.js

feat: swagger 文件 - likeController.js

---

controller/followController.js
controller/likeController.js
routes/users.js
swagger-defintion.js
swagger-output.json

新增 swagger 文件 - followController.js

feat: swagger 文件 - followController.js

---

swagger-defintion.js
swagger-output.json

fix: 修改 swagger 文件

---

controller/commentController.js
routes/posts.js
swagger-output.json

新增 swagger 文件 - commentController.js

feat: swagger 文件 - commentController.js

---

controller/commentController.js
controller/fileController.js
routes/posts.js
routes/users.js
swagger-output.json

新增 swagger 文件 - fileController.js

feat: swagger 文件 - fileController.js

---

routes/general.js
routes/posts.js
routes/users.js
swagger-output.json
swagger.js

feat: swagger 文件 - 404 路由

---

controller/authController.js
routes/auth.js
swagger-output.json

新增 swagger 文件 - 忽略 authController.js

feat: swagger 文件 - 忽略 authController.js

---

controller/likeController.js

fix: 修改 likeController.js 一頁顯示的筆數

---

controller/likeController.js

Fix like controllers

---

controller/postController.js

fix: getAllPosts 修正熱門貼文

---

controller/postController.js

1. getAllPosts 熱門貼文加上關鍵字搜尋 (sort=hot&q=<keywords>)

Dev-getAllPosts 熱門貼文加上關鍵字搜尋

---

utils/errorHandler.js

fix: 修訂 resErrorProd

---

middleware/auth.js

dev- 修正 auth.js 錯誤訊息

---

routes/users.js
swagger-output.json

fix: 修改 swagger

---

middleware/auth.js
routes/auth.js
routes/general.js

Dev- 修正錯誤訊息 

---

utils/passport.js

1. 修正新用戶透過 Google 登入，第一次會發生驗證錯誤的問題

1. fix-修正新用戶透過 Google 登入，會發生驗證錯誤
